#ifndef PRAGMA_BGUI_LIB_SFD_LIB_H
#define PRAGMA_BGUI_LIB_SFD_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
** Copyright 2025 amigazen project
** Copyright 1998 Manuel Lemos
** Copyright 1996-1997 Ian J. Einman
** Copyright 1993-1996 Jaba Development
** Copyright 1993-1996 Jan van den Baard
** All Rights Reserved
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_BGUI_LIB_SFD_PROTOS_H
#include <clib/bgui_lib.sfd_protos.h>
#endif /* CLIB_BGUI_LIB_SFD_PROTOS_H */

/* "bgui.library" */
/*--- functions in V40811 or higher --- */
#pragma amicall(BGUIBase, 0x1E, BGUI_GetClassPtr(d0))
#pragma amicall(BGUIBase, 0x24, BGUI_NewObjectA(d0,a0))
#pragma amicall(BGUIBase, 0x2A, BGUI_RequestA(a0,a1,a2))
#pragma amicall(BGUIBase, 0x30, BGUI_Help(a0,a1,a2,d0))
#pragma amicall(BGUIBase, 0x36, BGUI_LockWindow(a0))
#pragma amicall(BGUIBase, 0x3C, BGUI_UnlockWindow(a0))
#pragma amicall(BGUIBase, 0x42, BGUI_DoGadgetMethodA(a0,a1,a2,a3))
#pragma amicall(BGUIBase, 0x54, BGUI_AllocBitMap(d0,d1,d2,d3,a0))
#pragma amicall(BGUIBase, 0x5A, BGUI_FreeBitMap(a0))
#pragma amicall(BGUIBase, 0x60, BGUI_CreateRPortBitMap(a0,d0,d1,d2))
#pragma amicall(BGUIBase, 0x66, BGUI_FreeRPortBitMap(a0))
#pragma amicall(BGUIBase, 0x6C, BGUI_InfoTextSize(a0,a1,a2,a3))
#pragma amicall(BGUIBase, 0x72, BGUI_InfoText(a0,a1,a2,a3))
#pragma amicall(BGUIBase, 0x78, BGUI_GetLocaleStr(a0,d0))
#pragma amicall(BGUIBase, 0x7E, BGUI_GetCatalogStr(a0,d0,a1))
#pragma amicall(BGUIBase, 0x84, BGUI_FillRectPattern(a1,a0,d0,d1,d2,d3))
#pragma amicall(BGUIBase, 0x8A, BGUI_PostRender(a0,a2,a1))
#pragma amicall(BGUIBase, 0x90, BGUI_MakeClassA(a0))
#pragma amicall(BGUIBase, 0x96, BGUI_FreeClass(a0))
#pragma amicall(BGUIBase, 0x9C, BGUI_PackStructureTags(a0,a1,a2))
#pragma amicall(BGUIBase, 0xA2, BGUI_UnpackStructureTags(a0,a1,a2))

#endif /* PRAGMA_BGUI_LIB_SFD_LIB_H */
