#ifndef PRAGMAS_BGUI_LIB_SFD_PRAGMAS_H
#define PRAGMAS_BGUI_LIB_SFD_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
** Copyright 2025 amigazen project
** Copyright 1998 Manuel Lemos
** Copyright 1996-1997 Ian J. Einman
** Copyright 1993-1996 Jaba Development
** Copyright 1993-1996 Jan van den Baard
** All Rights Reserved
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_BGUI_LIB_SFD_PROTOS_H
#include <clib/bgui_lib.sfd_protos.h>
#endif /* CLIB_BGUI_LIB_SFD_PROTOS_H */

/* "bgui.library" */
/*--- functions in V40811 or higher --- */
#pragma libcall BGUIBase BGUI_GetClassPtr 1E 001
#pragma libcall BGUIBase BGUI_NewObjectA 24 8002
#pragma libcall BGUIBase BGUI_RequestA 2A A9803
#pragma libcall BGUIBase BGUI_Help 30 0A9804
#pragma libcall BGUIBase BGUI_LockWindow 36 801
#pragma libcall BGUIBase BGUI_UnlockWindow 3C 801
#pragma libcall BGUIBase BGUI_DoGadgetMethodA 42 BA9804
#pragma libcall BGUIBase BGUI_AllocBitMap 54 8321005
#pragma libcall BGUIBase BGUI_FreeBitMap 5A 801
#pragma libcall BGUIBase BGUI_CreateRPortBitMap 60 210804
#pragma libcall BGUIBase BGUI_FreeRPortBitMap 66 801
#pragma libcall BGUIBase BGUI_InfoTextSize 6C BA9804
#pragma libcall BGUIBase BGUI_InfoText 72 BA9804
#pragma libcall BGUIBase BGUI_GetLocaleStr 78 0802
#pragma libcall BGUIBase BGUI_GetCatalogStr 7E 90803
#pragma libcall BGUIBase BGUI_FillRectPattern 84 32108906
#pragma libcall BGUIBase BGUI_PostRender 8A 9A803
#pragma libcall BGUIBase BGUI_MakeClassA 90 801
#pragma libcall BGUIBase BGUI_FreeClass 96 801
#pragma libcall BGUIBase BGUI_PackStructureTags 9C A9803
#pragma libcall BGUIBase BGUI_UnpackStructureTags A2 A9803

#endif /* PRAGMAS_BGUI_LIB_SFD_PRAGMAS_H */
