#ifndef CLIB_BGUI_LIB_SFD_PROTOS_H
#define CLIB_BGUI_LIB_SFD_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
** Copyright 2025 amigazen project
** Copyright 1998 Manuel Lemos
** Copyright 1996-1997 Ian J. Einman
** Copyright 1993-1996 Jaba Development
** Copyright 1993-1996 Jan van den Baard
** All Rights Reserved
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* "bgui.library"*/
/*--- functions in V40811 or higher ---*/
APTR BGUI_GetClassPtr(ULONG );
APTR BGUI_NewObjectA(ULONG , struct TagItem *);
BOOL BGUI_RequestA(struct Window *, struct Requester *, APTR );
BOOL BGUI_Help(struct Window *, STRPTR , STRPTR , ULONG );
APTR BGUI_LockWindow(struct Window *);
void BGUI_UnlockWindow(APTR );
BOOL BGUI_DoGadgetMethodA(struct Gadget *, struct Window *, struct Requester *, struct IntuiMessage *);
struct BitMap *BGUI_AllocBitMap(ULONG , ULONG , ULONG , ULONG , struct BitMap *);
void BGUI_FreeBitMap(struct BitMap *);
struct BitMap *BGUI_CreateRPortBitMap(struct RastPort *, ULONG , ULONG , ULONG );
void BGUI_FreeRPortBitMap(struct RastPort *);
void BGUI_InfoTextSize(struct RastPort *, STRPTR , ULONG *, ULONG *);
void BGUI_InfoText(struct RastPort *, STRPTR , struct IBox *, struct DrawInfo *);
STRPTR BGUI_GetLocaleStr(struct Catalog *, ULONG );
STRPTR BGUI_GetCatalogStr(struct Catalog *, ULONG , STRPTR );
void BGUI_FillRectPattern(struct RastPort *, struct BitMap *, ULONG , ULONG , ULONG , ULONG );
void BGUI_PostRender(struct Class *, struct Gadget *, struct GP *);
struct Class *BGUI_MakeClassA(struct TagItem *);
void BGUI_FreeClass(struct Class *);
BOOL BGUI_PackStructureTags(APTR , struct TagItem *, struct TagItem *);
BOOL BGUI_UnpackStructureTags(APTR , struct TagItem *, struct TagItem *);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_BGUI_LIB_SFD_PROTOS_H */
