#ifndef INLINE_BGUI_LIB_SFD_PROTOS_H
#define INLINE_BGUI_LIB_SFD_PROTOS_H

/*
** VBCC format inline files.
**
** Copyright 2025 amigazen project
** Copyright 1998 Manuel Lemos
** Copyright 1996-1997 Ian J. Einman
** Copyright 1993-1996 Jaba Development
** Copyright 1993-1996 Jan van den Baard
** All Rights Reserved
**
** Generated by LibDescConverter from an sfd file
*/

/* "bgui.library" */
/*--- functions in V40811 or higher --- */
APTR __BGUI_GetClassPtr(__reg("a6") void *, __reg("d0") ULONG )="\tjsr\t-30(a6)";
#define BGUI_GetClassPtr() __BGUI_GetClassPtr(BGUIBase, ())

APTR __BGUI_NewObjectA(__reg("a6") void *, __reg("d0") ULONG , __reg("a0") struct TagItem *)="\tjsr\t-36(a6)";
#define BGUI_NewObjectA(, ) __BGUI_NewObjectA(BGUIBase, (), ())

BOOL __BGUI_RequestA(__reg("a6") void *, __reg("a0") struct Window *, __reg("a1") struct Requester *, __reg("a2") APTR )="\tjsr\t-42(a6)";
#define BGUI_RequestA(, , ) __BGUI_RequestA(BGUIBase, (), (), ())

BOOL __BGUI_Help(__reg("a6") void *, __reg("a0") struct Window *, __reg("a1") STRPTR , __reg("a2") STRPTR , __reg("d0") ULONG )="\tjsr\t-48(a6)";
#define BGUI_Help(, , , ) __BGUI_Help(BGUIBase, (), (), (), ())

APTR __BGUI_LockWindow(__reg("a6") void *, __reg("a0") struct Window *)="\tjsr\t-54(a6)";
#define BGUI_LockWindow() __BGUI_LockWindow(BGUIBase, ())

void __BGUI_UnlockWindow(__reg("a6") void *, __reg("a0") APTR )="\tjsr\t-60(a6)";
#define BGUI_UnlockWindow() __BGUI_UnlockWindow(BGUIBase, ())

BOOL __BGUI_DoGadgetMethodA(__reg("a6") void *, __reg("a0") struct Gadget *, __reg("a1") struct Window *, __reg("a2") struct Requester *, __reg("a3") struct IntuiMessage *)="\tjsr\t-66(a6)";
#define BGUI_DoGadgetMethodA(, , , ) __BGUI_DoGadgetMethodA(BGUIBase, (), (), (), ())

struct BitMap *__BGUI_AllocBitMap(__reg("a6") void *, __reg("d0") ULONG , __reg("d1") ULONG , __reg("d2") ULONG , __reg("d3") ULONG , __reg("a0") struct BitMap *)="\tjsr\t-84(a6)";
#define BGUI_AllocBitMap(, , , , ) __BGUI_AllocBitMap(BGUIBase, (), (), (), (), ())

void __BGUI_FreeBitMap(__reg("a6") void *, __reg("a0") struct BitMap *)="\tjsr\t-90(a6)";
#define BGUI_FreeBitMap() __BGUI_FreeBitMap(BGUIBase, ())

struct BitMap *__BGUI_CreateRPortBitMap(__reg("a6") void *, __reg("a0") struct RastPort *, __reg("d0") ULONG , __reg("d1") ULONG , __reg("d2") ULONG )="\tjsr\t-96(a6)";
#define BGUI_CreateRPortBitMap(, , , ) __BGUI_CreateRPortBitMap(BGUIBase, (), (), (), ())

void __BGUI_FreeRPortBitMap(__reg("a6") void *, __reg("a0") struct RastPort *)="\tjsr\t-102(a6)";
#define BGUI_FreeRPortBitMap() __BGUI_FreeRPortBitMap(BGUIBase, ())

void __BGUI_InfoTextSize(__reg("a6") void *, __reg("a0") struct RastPort *, __reg("a1") STRPTR , __reg("a2") ULONG *, __reg("a3") ULONG *)="\tjsr\t-108(a6)";
#define BGUI_InfoTextSize(, , , ) __BGUI_InfoTextSize(BGUIBase, (), (), (), ())

void __BGUI_InfoText(__reg("a6") void *, __reg("a0") struct RastPort *, __reg("a1") STRPTR , __reg("a2") struct IBox *, __reg("a3") struct DrawInfo *)="\tjsr\t-114(a6)";
#define BGUI_InfoText(, , , ) __BGUI_InfoText(BGUIBase, (), (), (), ())

STRPTR __BGUI_GetLocaleStr(__reg("a6") void *, __reg("a0") struct Catalog *, __reg("d0") ULONG )="\tjsr\t-120(a6)";
#define BGUI_GetLocaleStr(, ) __BGUI_GetLocaleStr(BGUIBase, (), ())

STRPTR __BGUI_GetCatalogStr(__reg("a6") void *, __reg("a0") struct Catalog *, __reg("d0") ULONG , __reg("a1") STRPTR )="\tjsr\t-126(a6)";
#define BGUI_GetCatalogStr(, , ) __BGUI_GetCatalogStr(BGUIBase, (), (), ())

void __BGUI_FillRectPattern(__reg("a6") void *, __reg("a1") struct RastPort *, __reg("a0") struct BitMap *, __reg("d0") ULONG , __reg("d1") ULONG , __reg("d2") ULONG , __reg("d3") ULONG )="\tjsr\t-132(a6)";
#define BGUI_FillRectPattern(, , , , , ) __BGUI_FillRectPattern(BGUIBase, (), (), (), (), (), ())

void __BGUI_PostRender(__reg("a6") void *, __reg("a0") struct Class *, __reg("a2") struct Gadget *, __reg("a1") struct GP *)="\tjsr\t-138(a6)";
#define BGUI_PostRender(, , ) __BGUI_PostRender(BGUIBase, (), (), ())

struct Class *__BGUI_MakeClassA(__reg("a6") void *, __reg("a0") struct TagItem *)="\tjsr\t-144(a6)";
#define BGUI_MakeClassA() __BGUI_MakeClassA(BGUIBase, ())

void __BGUI_FreeClass(__reg("a6") void *, __reg("a0") struct Class *)="\tjsr\t-150(a6)";
#define BGUI_FreeClass() __BGUI_FreeClass(BGUIBase, ())

BOOL __BGUI_PackStructureTags(__reg("a6") void *, __reg("a0") APTR , __reg("a1") struct TagItem *, __reg("a2") struct TagItem *)="\tjsr\t-156(a6)";
#define BGUI_PackStructureTags(, , ) __BGUI_PackStructureTags(BGUIBase, (), (), ())

BOOL __BGUI_UnpackStructureTags(__reg("a6") void *, __reg("a0") APTR , __reg("a1") struct TagItem *, __reg("a2") struct TagItem *)="\tjsr\t-162(a6)";
#define BGUI_UnpackStructureTags(, , ) __BGUI_UnpackStructureTags(BGUIBase, (), (), ())


#endif /* INLINE_BGUI_LIB_SFD_PROTOS_H */
